아메리카노를 제거한 데이터에서 유클리디안 거리 사용

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [74]:
import pandas as pd
import numpy as np

feature_with_weather = pd.read_csv('/content/drive/MyDrive/KHUDA/카페데이터/최종/feature_by_weather_without_iceamericano.csv', encoding = 'cp949')
feature_with_avg_weather = pd.read_csv('/content/drive/MyDrive/KHUDA/카페데이터/최종/ratio_features_without_iceamericano.csv', encoding = 'cp949')
feature = pd.read_csv('/content/drive/MyDrive/KHUDA/카페데이터/최종/features_without_iceamericano.csv', encoding = 'cp949')

In [75]:
feature_weather = feature_with_weather.drop(['기온', '흐림', '비소나기눈'], axis=1)
print(feature_weather.shape)
feature_weather.head()

(16, 11)

,has_coffee,has_milk,caffeine,is_carbonated,is_hot,has_chocolate,is_syrup_based,is_tea_variant,sugar,has_fruit,is_powdered
0,0.739020,0.483953,0.822635,0.046453,0.581926,0.058277,0.289696,0.054054,0.597973,0.154561,0.252534
1,0.733696,0.528986,0.831522,0.048913,0.617754,0.045290,0.297101,0.043478,0.634058,0.157609,0.266304
2,0.694030,0.511194,0.776119,0.067164,0.496269,0.052239,0.309701,0.033582,0.660448,0.190299,0.302239
3,0.753695,0.445813,0.832512,0.051724,0.633005,0.054187,0.270936,0.046798,0.551724,0.140394,0.238916
4,0.664896,0.520446,0.734997,0.077005,0.450876,0.035582,0.329262,0.052045,0.700478,0.229952,0.281466

In [76]:
drink_feature= feature.drop(['Unnamed: 0'], axis=1)
print(drink_feature.shape)
drink_feature.head()

(37, 12)

,items,has_coffee,has_milk,caffeine,is_carbonated,is_hot,has_chocolate,is_syrup_based,is_tea_variant,sugar,has_fruit,is_powdered
0,아메리카노,1,0,1,0,1,0,0,0,0,0,0
1,아이스 카페라떼,1,1,1,0,0,0,0,0,1,0,0
2,아이스 바닐라라떼,1,1,1,0,0,0,1,0,1,0,1
3,카페라떼,1,1,1,0,1,0,0,0,1,0,0
4,아이스티복숭아,0,0,0,0,0,0,0,0,1,1,1

In [77]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

def find_similarity(numpy_feature, drink_feature):
  answer = []
  for i in range(37):
    drink_feature_solo = drink_feature.iloc[i,1:]
    numpy_drink_feature = drink_feature_solo.to_numpy()
    numpy_drink_feature = numpy_drink_feature.astype(float)
    value = euclidean_distance(numpy_feature, numpy_drink_feature)
    answer.append(value)
  return answer

def get_min_indices(lst, n):
    min_indices = []
    sorted_indices = sorted(range(len(lst)), key=lambda i: lst[i])
    for i in range(n):
        min_indices.append(sorted_indices[i])
    return min_indices

def get_items(min_indices):
  min_items = []
  for i in range(len(min_indices)):
    min_items.append(drink_feature.loc[min_indices[i], 'items'])
  return min_items

def recommend_drink_by_weather(feature_weather,drink_feature):
  lst=[]
  for i in range(len(feature_weather)):
    numpy_feature = feature_weather.iloc[i]
    value = find_similarity(numpy_feature, drink_feature)
    lst.append(value)
  return lst

In [78]:
recommend = recommend_drink_by_weather(feature_weather,drink_feature)

In [79]:
indices = []
for i in range(len(recommend)):
  value = get_min_indices(recommend[i], 3)
  indices.append(value)

indices

[[3, 0, 1],
 [3, 1, 22],
 [1, 22, 3],
 [0, 30, 3],
 [1, 22, 3],
 [1, 22, 3],
 [3, 1, 22],
 [1, 22, 3],
 [1, 22, 11],
 [1, 22, 11],
 [1, 22, 11],
 [1, 22, 11],
 [1, 22, 11],
 [1, 22, 11],
 [1, 22, 11],
 [1, 22, 11]]

In [80]:
min_items = []
for j in range(len(indices)):
  value = get_items(indices[j])
  min_items.append(value)

for i in range(16):
  print(i, min_items[i])

0 ['카페라떼', '아메리카노', '아이스 카페라떼']
1 ['카페라떼', '아이스 카페라떼', '콜드브루라떼블랜딩']
2 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼']
3 ['아메리카노', '에스프레소', '카페라떼']
4 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼']
5 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼']
6 ['카페라떼', '아이스 카페라떼', '콜드브루라떼블랜딩']
7 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼']
8 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또']
9 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또']
10 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또']
11 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또']
12 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또']
13 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또']
14 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또']
15 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또']

표준화한 데이터에 대한 음료 추천

In [81]:
feature_avg_weather = feature_with_avg_weather.drop(['기온', '흐림', '비소나기눈'], axis=1)
print(feature_avg_weather.shape)
feature_avg_weather.head()

(16, 11)

,has_coffee,has_milk,caffeine,is_carbonated,is_hot,has_chocolate,is_syrup_based,is_tea_variant,sugar,has_fruit,is_powdered
0,0.594994,0.458353,0.600119,0.450810,0.704727,0.516174,0.441260,0.503027,0.380309,0.409910,0.475569
1,0.589669,0.503386,0.609006,0.453271,0.740555,0.503186,0.448665,0.492452,0.416394,0.412958,0.489340
2,0.550003,0.485594,0.553604,0.471522,0.619070,0.510135,0.461265,0.482555,0.442783,0.445648,0.525274
3,0.609668,0.420213,0.609997,0.456082,0.755807,0.512084,0.422500,0.495771,0.334060,0.395744,0.461952
4,0.520870,0.494846,0.512482,0.481362,0.573678,0.493478,0.480826,0.501018,0.482814,0.485302,0.504501

In [82]:
avg_recommend = recommend_drink_by_weather(feature_avg_weather,drink_feature)

In [83]:
avg_indices = []
for i in range(len(avg_recommend)):
  value = get_min_indices(avg_recommend[i], 6)
  avg_indices.append(value)

avg_indices

[[0, 30, 3, 18, 36, 8],
 [0, 30, 3, 18, 13, 24],
 [0, 30, 18, 3, 13, 24],
 [0, 30, 36, 3, 8, 14],
 [0, 30, 18, 3, 36, 13],
 [20, 26, 33, 35, 6, 7],
 [36, 0, 30, 20, 26, 33],
 [0, 30, 18, 3, 24, 32],
 [6, 7, 9, 16, 5, 4],
 [5, 28, 29, 6, 7, 9],
 [11, 1, 22, 5, 6, 7],
 [19, 5, 12, 21, 10, 15],
 [6, 7, 9, 16, 5, 28],
 [5, 6, 7, 9, 16, 28],
 [6, 7, 9, 16, 28, 29],
 [5, 6, 7, 9, 16, 28]]

In [84]:
avg_min_items = []
for j in range(len(avg_indices)):
  value = get_items(avg_indices[j])
  avg_min_items.append(value)

for i in range(16):
  print(i, avg_min_items[i])

0 ['아메리카노', '에스프레소', '카페라떼', '카푸치노', '크리스틴 캐모마일', '콜드브루블랜딩']
1 ['아메리카노', '에스프레소', '카페라떼', '카푸치노', '바닐라라떼', '밀크티']
2 ['아메리카노', '에스프레소', '카푸치노', '카페라떼', '바닐라라떼', '밀크티']
3 ['아메리카노', '에스프레소', '크리스틴 캐모마일', '카페라떼', '콜드브루블랜딩', '콜드브루싱글']
4 ['아메리카노', '에스프레소', '카푸치노', '카페라떼', '크리스틴 캐모마일', '바닐라라떼']
5 ['유자차', '레몬차', '모과차', '자몽차', '레몬에이드', '자몽에이드']
6 ['크리스틴 캐모마일', '아메리카노', '에스프레소', '유자차', '레몬차', '모과차']
7 ['아메리카노', '에스프레소', '카푸치노', '카페라떼', '밀크티', '그린티라떼']
8 ['레몬에이드', '자몽에이드', '청포도에이드', '유자에이드', '딸기라떼', '아이스티복숭아']
9 ['딸기라떼', '아이스 레몬차', '아이스 유자차', '레몬에이드', '자몽에이드', '청포도에이드']
10 ['아이스 카라멜마끼아또', '아이스 카페라떼', '콜드브루라떼블랜딩', '딸기라떼', '레몬에이드', '자몽에이드']
11 ['아이스 오곡라떼', '딸기라떼', '아이스 초코라떼', '아이스 민트초코라떼', '아이스 밀크티', '아이스 그린티라떼']
12 ['레몬에이드', '자몽에이드', '청포도에이드', '유자에이드', '딸기라떼', '아이스 레몬차']
13 ['딸기라떼', '레몬에이드', '자몽에이드', '청포도에이드', '유자에이드', '아이스 레몬차']
14 ['레몬에이드', '자몽에이드', '청포도에이드', '유자에이드', '아이스 레몬차', '아이스 유자차']
15 ['딸기라떼', '레몬에이드', '자몽에이드', '청포도에이드', '유자에이드', '아이스 레몬차']

원래 자료에서 상위 3개와 표준화 자료 상위 3개 (총6개) 추천

In [85]:
# min_items, avg_min_items

for i in range(len(avg_min_items)):
  count = 0
  for j in range(len(avg_min_items[i])):
    if avg_min_items[i][j] not in min_items[i]:
      min_items[i].append(avg_min_items[i][j])
      count = count +1
    else:
      continue;
    if count == 3:
      break;

In [86]:
for i in range(16):
  print(i, min_items[i])

0 ['카페라떼', '아메리카노', '아이스 카페라떼', '에스프레소', '카푸치노', '크리스틴 캐모마일']
1 ['카페라떼', '아이스 카페라떼', '콜드브루라떼블랜딩', '아메리카노', '에스프레소', '카푸치노']
2 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼', '아메리카노', '에스프레소', '카푸치노']
3 ['아메리카노', '에스프레소', '카페라떼', '크리스틴 캐모마일', '콜드브루블랜딩', '콜드브루싱글']
4 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼', '아메리카노', '에스프레소', '카푸치노']
5 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼', '유자차', '레몬차', '모과차']
6 ['카페라떼', '아이스 카페라떼', '콜드브루라떼블랜딩', '크리스틴 캐모마일', '아메리카노', '에스프레소']
7 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼', '아메리카노', '에스프레소', '카푸치노']
8 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '레몬에이드', '자몽에이드', '청포도에이드']
9 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '딸기라떼', '아이스 레몬차', '아이스 유자차']
10 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '딸기라떼', '레몬에이드', '자몽에이드']
11 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '아이스 오곡라떼', '딸기라떼', '아이스 초코라떼']
12 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '레몬에이드', '자몽에이드', '청포도에이드']
13 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '딸기라떼', '레몬에이드', '자몽에이드']
14 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '레몬에이드', '자몽에이드', '청포도에이드']
15 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '딸기라떼', '레몬에이드', '자몽에이드']

카페인 특성 제거 후 추천

In [14]:
feature_weather_without_cof = feature_weather.drop(['has_coffee','caffeine'], axis=1)
print(feature_weather_without_cof.shape)
feature_weather_without_cof.head()

(16, 9)

,has_milk,is_carbonated,is_hot,has_chocolate,is_syrup_based,is_tea_variant,sugar,has_fruit,is_powdered
0,0.483953,0.046453,0.581926,0.058277,0.289696,0.054054,0.597973,0.154561,0.252534
1,0.528986,0.048913,0.617754,0.045290,0.297101,0.043478,0.634058,0.157609,0.266304
2,0.511194,0.067164,0.496269,0.052239,0.309701,0.033582,0.660448,0.190299,0.302239
3,0.445813,0.051724,0.633005,0.054187,0.270936,0.046798,0.551724,0.140394,0.238916
4,0.520446,0.077005,0.450876,0.035582,0.329262,0.052045,0.700478,0.229952,0.281466

In [15]:
drink_feature_without_cof= drink_feature.drop(['has_coffee','caffeine'], axis=1)
print(drink_feature_without_cof.shape)
drink_feature_without_cof.head()

(37, 10)

,items,has_milk,is_carbonated,is_hot,has_chocolate,is_syrup_based,is_tea_variant,sugar,has_fruit,is_powdered
0,아메리카노,0,0,1,0,0,0,0,0,0
1,아이스 카페라떼,1,0,0,0,0,0,1,0,0
2,아이스 바닐라라떼,1,0,0,0,1,0,1,0,1
3,카페라떼,1,0,1,0,0,0,1,0,0
4,아이스티복숭아,0,0,0,0,0,0,1,1,1

In [16]:
recommend_without_cof = recommend_drink_by_weather(feature_weather_without_cof,drink_feature_without_cof)

In [17]:
indices_without_cof = []
for i in range(len(recommend_without_cof)):
  value = get_min_indices(recommend_without_cof[i], 10)
  indices_without_cof.append(value)

indices_without_cof

[[3, 0, 1, 22, 30, 8, 14, 27, 18, 23],
 [3, 1, 22, 0, 30, 18, 23, 24, 32, 8],
 [1, 22, 3, 8, 14, 27, 0, 30, 11, 10],
 [0, 30, 3, 8, 14, 27, 1, 22, 18, 23],
 [1, 22, 3, 11, 10, 15, 19, 8, 14, 27],
 [1, 22, 3, 11, 8, 14, 27, 0, 30, 10],
 [3, 1, 22, 0, 30, 8, 14, 27, 11, 18],
 [1, 22, 3, 11, 10, 15, 19, 8, 14, 27],
 [1, 22, 11, 10, 15, 19, 3, 8, 14, 27],
 [1, 22, 11, 10, 15, 19, 2, 5, 3, 8],
 [1, 22, 11, 3, 10, 15, 19, 5, 8, 14],
 [1, 22, 11, 3, 10, 15, 19, 8, 14, 27],
 [1, 22, 11, 10, 15, 19, 5, 2, 3, 8],
 [1, 22, 11, 10, 15, 19, 2, 5, 3, 8],
 [1, 22, 11, 8, 14, 27, 3, 10, 15, 19],
 [1, 22, 11, 10, 15, 19, 3, 5, 2, 8]]

In [18]:
min_items_without_cof = []
for j in range(len(indices_without_cof)):
  value = get_items(indices_without_cof[j])
  min_items_without_cof.append(value)

for i in range(16):
  print(i, min_items_without_cof[i])

0 ['카페라떼', '아메리카노', '아이스 카페라떼', '콜드브루라떼블랜딩', '에스프레소', '콜드브루블랜딩', '콜드브루싱글', '피지워터', '카푸치노', '오곡라떼']
1 ['카페라떼', '아이스 카페라떼', '콜드브루라떼블랜딩', '아메리카노', '에스프레소', '카푸치노', '오곡라떼', '밀크티', '그린티라떼', '콜드브루블랜딩']
2 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼', '콜드브루블랜딩', '콜드브루싱글', '피지워터', '아메리카노', '에스프레소', '아이스 카라멜마끼아또', '아이스 밀크티']
3 ['아메리카노', '에스프레소', '카페라떼', '콜드브루블랜딩', '콜드브루싱글', '피지워터', '아이스 카페라떼', '콜드브루라떼블랜딩', '카푸치노', '오곡라떼']
4 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼', '아이스 카라멜마끼아또', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '콜드브루블랜딩', '콜드브루싱글', '피지워터']
5 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼', '아이스 카라멜마끼아또', '콜드브루블랜딩', '콜드브루싱글', '피지워터', '아메리카노', '에스프레소', '아이스 밀크티']
6 ['카페라떼', '아이스 카페라떼', '콜드브루라떼블랜딩', '아메리카노', '에스프레소', '콜드브루블랜딩', '콜드브루싱글', '피지워터', '아이스 카라멜마끼아또', '카푸치노']
7 ['아이스 카페라떼', '콜드브루라떼블랜딩', '카페라떼', '아이스 카라멜마끼아또', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '콜드브루블랜딩', '콜드브루싱글', '피지워터']
8 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '카페라떼', '콜드브루블랜딩', '콜드브루싱글', '피지워터']
9 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '아이스 바닐라라떼', '딸기라떼', '카페라떼', '콜드브루블랜딩']
10 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '카페라떼', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '딸기라떼', '콜드브루블랜딩', '콜드브루싱글']
11 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '카페라떼', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '콜드브루블랜딩', '콜드브루싱글', '피지워터']
12 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '딸기라떼', '아이스 바닐라라떼', '카페라떼', '콜드브루블랜딩']
13 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '아이스 바닐라라떼', '딸기라떼', '카페라떼', '콜드브루블랜딩']
14 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '콜드브루블랜딩', '콜드브루싱글', '피지워터', '카페라떼', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼']
15 ['아이스 카페라떼', '콜드브루라떼블랜딩', '아이스 카라멜마끼아또', '아이스 밀크티', '아이스 그린티라떼', '아이스 오곡라떼', '카페라떼', '딸기라떼', '아이스 바닐라라떼', '콜드브루블랜딩']